apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aayo2hr7y-python 
  janus-idp.io/tekton: aayo2hr7y-python
  backstage.io/kubernetes-id: aayo2hr7y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aayo2hr7y-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml